## GOBAI-O2-v1.0 (vertical mean: 0-200m; 200-600m)

In [1]:
import os
import xarray as xr
import numpy as np
import netCDF4
import seawater as sw
USER = os.environ['USER']

In [2]:
## monthly gridded O2/T/S data; 2004-2021
a1,a2,b1,b2 = [79, 131, 149, 301]
path = f'/glade/u/home/{USER}/O2prediction/Prediction/DATA'
filename = f'{path}/GOBAI-O2-clim-v1.0.nc'
nc = netCDF4.Dataset(filename, 'r')
pres = nc.variables['pres'][:]
lat = nc.variables['lat'][a1:a2]
lon = nc.variables['lon'][b1:b2]
o2_clim = nc.variables['oxy'][:,:,a1:a2,b1:b2]
temp_clim = nc.variables['temp'][:,:,a1:a2,b1:b2]
salt_clim = nc.variables['sal'][:,:,a1:a2,b1:b2]
nc.close()
#
filename = f'{path}/GOBAI-O2-v1.0.nc'
nc = netCDF4.Dataset(filename, 'r')
o2 = nc.variables['oxy'][:,:,a1:a2,b1:b2]
temp = nc.variables['temp'][:,:,a1:a2,b1:b2]
salt = nc.variables['sal'][:,:,a1:a2,b1:b2]
nc.close()

In [3]:
# transfer dbar to m
z_r = sw.dpth(pres,lat=0.)
z_r

masked_array(data=[2.48625111579895, 9.94482421875, 19.889163970947266,
                   29.833023071289062, 39.776397705078125,
                   49.719295501708984, 59.661712646484375,
                   69.60364532470703, 79.54508972167969,
                   89.48605346679688, 99.42654418945312,
                   109.3665542602539, 119.30608367919922, 129.2451171875,
                   139.18368530273438, 149.12176513671875,
                   159.05935668945312, 168.99649047851562,
                   181.41722106933594, 198.8049774169922,
                   218.67489624023438, 238.54287719726562,
                   258.40899658203125, 278.2731628417969,
                   298.13543701171875, 317.9958190917969,
                   337.854248046875, 357.71075439453125,
                   377.56536865234375, 397.4180603027344,
                   417.26885986328125, 437.1177673339844,
                   459.4454345703125, 496.6529846191406,
                   546.2526245117188, 595

In [4]:
z_w = (z_r[1:] + z_r[:-1])*0.5
dz = z_w[1:] - z_w[:-1]
dz = [z_r[0]] + list(dz) + [dz[-1]]
dz = np.array(dz)
dz

array([ 2.486251,  8.701456,  9.944099,  9.943617,  9.943138,  9.942657,
        9.942169,  9.941696,  9.9412  ,  9.940727,  9.940247,  9.939774,
        9.939285,  9.938797,  9.938324,  9.937836,  9.937363, 11.178925,
       14.904251, 18.62883 , 19.868958, 19.86705 , 19.865128, 19.86322 ,
       19.861328, 19.859436, 19.857452, 19.85556 , 19.853638, 19.851746,
       19.849854, 21.088318, 29.767578, 43.403625, 49.59369 , 49.581787,
       49.569946, 49.558167, 49.546387, 49.534607, 49.522705, 49.510986,
       49.499268, 49.48755 , 49.47583 , 49.46411 , 49.452637, 49.440796,
       49.429077, 49.41748 , 55.5802  , 74.082886, 92.56824 , 98.69641 ,
       98.65039 , 98.60449 , 86.24402 , 86.24402 ], dtype=float32)

In [5]:
nmon,nver,nlat,nlon = np.shape(salt)
nyear = int(nmon/12)
lon
#salt_clim = np.tile(salt_clim[np.newaxis,:,:,:,:],[nyear,1,1,1,1])
#salt = np.reshape(salt_clim, [nmon,nver,nlat,nlon])

masked_array(data=[ 169.5,  170.5,  171.5,  172.5,  173.5,  174.5,  175.5,
                    176.5,  177.5,  178.5,  179.5, -179.5, -178.5, -177.5,
                   -176.5, -175.5, -174.5, -173.5, -172.5, -171.5, -170.5,
                   -169.5, -168.5, -167.5, -166.5, -165.5, -164.5, -163.5,
                   -162.5, -161.5, -160.5, -159.5, -158.5, -157.5, -156.5,
                   -155.5, -154.5, -153.5, -152.5, -151.5, -150.5, -149.5,
                   -148.5, -147.5, -146.5, -145.5, -144.5, -143.5, -142.5,
                   -141.5, -140.5, -139.5, -138.5, -137.5, -136.5, -135.5,
                   -134.5, -133.5, -132.5, -131.5, -130.5, -129.5, -128.5,
                   -127.5, -126.5, -125.5, -124.5, -123.5, -122.5, -121.5,
                   -120.5, -119.5, -118.5, -117.5, -116.5, -115.5, -114.5,
                   -113.5, -112.5, -111.5, -110.5, -109.5, -108.5, -107.5,
                   -106.5, -105.5, -104.5, -103.5, -102.5, -101.5, -100.5,
                    -99.5

In [6]:
lat

masked_array(data=[14.5, 15.5, 16.5, 17.5, 18.5, 19.5, 20.5, 21.5, 22.5,
                   23.5, 24.5, 25.5, 26.5, 27.5, 28.5, 29.5, 30.5, 31.5,
                   32.5, 33.5, 34.5, 35.5, 36.5, 37.5, 38.5, 39.5, 40.5,
                   41.5, 42.5, 43.5, 44.5, 45.5, 46.5, 47.5, 48.5, 49.5,
                   50.5, 51.5, 52.5, 53.5, 54.5, 55.5, 56.5, 57.5, 58.5,
                   59.5, 60.5, 61.5, 62.5, 63.5, 64.5, 65.5],
             mask=False,
       fill_value=1e+20,
            dtype=float32)

In [7]:
from math import sin, cos, sqrt, atan2, radians
def geo_dis(lat1,lon1,lat2,lon2):
    # approximate radius of earth in km
    R = 6373.0

    lat1 = radians(lat1)
    lon1 = radians(lon1)
    lat2 = radians(lat2)
    lon2 = radians(lon2)

    dlon = lon2 - lon1
    dlat = lat2 - lat1

    a = sin(dlat / 2)**2 + cos(lat1) * cos(lat2) * sin(dlon / 2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))

    return R * c

In [8]:
lon1 = lon + 0.5
lon1 = list(lon1)
lon1 = [lon1[0]-1] + lon1
lon1 = np.array(lon1)
lat1 = lat + 0.5
lat1 = list(lat1)
lat1 = [lat1[0]-1] + lat1
lat1 = np.array(lat1)
lat1

array([14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51., 52.,
       53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64., 65.,
       66.])

In [26]:
dx = np.zeros([nlat,nlon])
dy = dx.copy()
for ii in range(nlat):
    for jj in range(nlon):
        dx[ii,jj] = geo_dis(lat[ii],lon1[ii],lat[ii],lon1[ii+1])
        dy[ii,jj] = geo_dis(lat1[ii],lon[ii],lat1[ii+1],lon[ii])
darea = dx*dy # unit km*km

In [27]:
darea

array([[11977.98646161, 11977.98646161, 11977.98646161, ...,
        11977.98646161, 11977.98646161, 11977.98646161],
       [11922.09820353, 11922.09820353, 11922.09820353, ...,
        11922.09820353, 11922.09820353, 11922.09820353],
       [11862.57829301, 11862.57829301, 11862.57829301, ...,
        11862.57829301, 11862.57829301, 11862.57829301],
       ...,
       [ 5520.33704836,  5520.33704836,  5520.33704836, ...,
         5520.33704836,  5520.33704836,  5520.33704836],
       [ 5326.2608484 ,  5326.2608484 ,  5326.2608484 , ...,
         5326.2608484 ,  5326.2608484 ,  5326.2608484 ],
       [ 5130.56231078,  5130.56231078,  5130.56231078, ...,
         5130.56231078,  5130.56231078,  5130.56231078]])

In [10]:
dz = np.tile(dz[np.newaxis, :, np.newaxis, np.newaxis], [nmon, 1, nlat, nlon])
darea = np.tile(darea[np.newaxis, np.newaxis, :, :], [nmon, nver, 1, 1])
dvol = dz * darea
dvol = np.ma.array(dvol, mask=np.isnan(o2))
uo2 = o2 * dvol
np.shape(uo2)

(216, 58, 52, 152)

## Upper 200 m Vertical Mean

In [11]:
o2_200m = np.sum(uo2[:, :20], axis=1) / np.sum(dvol[:, :20], axis=1)
o2_600m = np.sum(uo2[:, 20:36], axis=1) / np.sum(dvol[:, 20:36], axis=1)

In [12]:
dsf = xr.Dataset()
time = range(nmon)
dsf['O2_0-200m'] = xr.DataArray(data=o2_200m, coords=dict(time=('time', time), lat=('lat', lat), lon=('lon', lon)), dims=('time','lat','lon'))
dsf['O2_200-600m'] = xr.DataArray(data=o2_600m, coords=dict(time=('time', time), lat=('lat', lat), lon=('lon', lon)), dims=('time','lat','lon'))

In [13]:
dsf.load()

<xarray.Dataset>
Dimensions:      (time: 216, lat: 52, lon: 152)
Coordinates:
  * time         (time) int64 0 1 2 3 4 5 6 7 ... 209 210 211 212 213 214 215
  * lat          (lat) float32 14.5 15.5 16.5 17.5 18.5 ... 62.5 63.5 64.5 65.5
  * lon          (lon) float32 169.5 170.5 171.5 172.5 ... -41.5 -40.5 -39.5
Data variables:
    O2_0-200m    (time, lat, lon) float64 196.8 197.4 197.3 ... 0.0 0.0 0.0
    O2_200-600m  (time, lat, lon) float64 91.05 91.82 93.0 92.72 ... 0.0 0.0 0.0

In [14]:
dsf.to_netcdf(f'{path}/GOBAI_O2_vertical_mean_2004-2016_monthly.nc', mode='w')

# Calculate LME-averaged O2

In [15]:
datadir = f'/glade/u/home/{USER}/O2prediction/Prediction/notebooks/data'
filename = '%s/LME-mask-POP_gx1v6.nc' % datadir
ds1 = xr.open_dataset(filename)
lme_mask = ds1['lme_mask']
lme = [1,2,3,4,5,6,7,8,9,10,65]

In [16]:
ds1

<xarray.Dataset>
Dimensions:   (nlat: 384, nlon: 320)
Coordinates:
    TLONG     (nlat, nlon) float64 ...
    TLAT      (nlat, nlon) float64 ...
Dimensions without coordinates: nlat, nlon
Data variables:
    lme_mask  (nlat, nlon) float64 ...
    KMT       (nlat, nlon) int32 ...
    TAREA     (nlat, nlon) float64 ...
Attributes:
    regrid_method:  nearest_s2d

In [24]:
tlon = ds1['TLONG'].values
tlat = ds1['TLAT'].values

In [25]:
tlon

array([[320.56250892, 321.68750895, 322.81250898, ..., 317.18750883,
        318.31250886, 319.43750889],
       [320.56250892, 321.68750895, 322.81250898, ..., 317.18750883,
        318.31250886, 319.43750889],
       [320.56250892, 321.68750895, 322.81250898, ..., 317.18750883,
        318.31250886, 319.43750889],
       ...,
       [320.25133086, 320.75380113, 321.25577325, ..., 318.74424456,
        319.24621668, 319.74869143],
       [320.23459477, 320.70358949, 321.17207442, ..., 318.82794339,
        319.29642832, 319.76542721],
       [320.21650899, 320.6493303 , 321.08163473, ..., 318.91838308,
        319.3506875 , 319.78351267]])

In [8]:
boxPhi = xr.Dataset()
phi_box1 = np.ma.zeros([len(lme), nmon])
phi_box1.mask = True
phi_box2 = phi_box1.copy()
for nn,box in zip(range(len(lme)),lme):
    print(box)
    latloc, lonloc = np.where(lme_mask == box)
    tmp1 = 0
    tmp2 = 0
    for bb in range(len(latloc)):
        rlon = tlon.isel(nlat=latloc[bb], nlon=lonloc[bb])
        rlat = tlat.isel(nlat=latloc[bb], nlon=lonloc[bb])
        
        tmp1 = tmp1 + dsf[f'{var}_0-200m'].isel(nlat=latloc[bb], nlon=lonloc[bb])
        tmp2 = tmp2 + dsf[f'{var}_200-600m'].isel(nlat=latloc[bb], nlon=lonloc[bb])
    phi_box1[nn] = tmp1/float(len(latloc))
    phi_box2[nn] = tmp2/float(len(latloc))
boxPhi[f'{var}_0-200m'] = xr.DataArray(data=phi_box1, coords=dict(lme=('lme', lme), time=('time', dsf.coords['time'].values)), dims=('lme','time'))
boxPhi[f'{var}_200-600m'] = xr.DataArray(data=phi_box2, coords=dict(lme=('lme', lme), time=('time', dsf.coords['time'].values)), dims=('lme','time'))

TEMP
1
2
3
4
5
6
7
8
9
10
65
O2
1
2
3
4
5
6
7
8
9
10
65
